##
## DO NOT MODIFY!
## AUTOGENERATED by scripts/generate_version.py on February 02, 2021 @ 16:58:09 EST
##

# RL-Scope pip package version:
# $ pip install rlscope==0.0.1 -f https://uoft-ecosystem.github.io/rlscope/whl
__version__ = "0.0.1"

__all__ = []

from rlscope import \
  version
__all__.extend([
  'version',
])
