##
## DO NOT MODIFY!
## AUTOGENERATED by scripts/generate_version.py on February 02, 2021 @ 16:58:09 EST
##

# RL-Scope pip package version:
# $ pip install rlscope==0.0.1 -f https://uoft-ecosystem.github.io/rlscope/whl
# (synonym for rlscope.__version__)
rlscope = "0.0.1"

# CUDA version.
# NOTE: your DL framework (e.g., PyTorch, TensorFlow) CUDA version should match this.
cuda = "10.1"

# Git commit hash
git_version = "9f745d14811efcad9e6ec65dc68423017b52ceca"

# Is this a debug build?
debug = False 
