# DO NOT MODIFY!
# This placeholder file will be autogenerated by rlscope/scripts/generate_version.py
# when building the wheel file with build_wheel.sh.

rlscope_version = None
cuda = None
git_version = None
debug = None

