#ifndef IML_DEFINES_H
#define IML_DEFINES_H

#define USEC_IN_MS (1000)
#define USEC_IN_SEC (USEC_IN_MS*1000)
#define PSEC_IN_USEC (1000)

#define OPERATION_UNKNOWN "OPERATION_UNKNOWN"

#endif //IML_DEFINES_H
